name: bc-monitor
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy=0.1.12
  - cartopy=0.20.2
  - cmocean=2.0
  - dask-ml=2022.5.27
  - gsw=3.4.0
  - ipykernel=6.13.0
  - matplotlib=3.5.1
  - motuclient=1.8.8
  - netCDF4=1.5.8
  - regionmask=0.9.0
  - scikit-learn=1.2.1
  - seaborn=0.11.2
  - tqdm=4.64.0
  - xarray=2022.3.0
  - xhistogram=0.3.2
  - pip
  - pip:
    - git+https://github.com/obidam/pyxpcm.git@master
#    - git+https://github.com/euroargodev/argopy.git@master
