name: bc-monitor
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy
  - cartopy
  - dask-ml
  - matplotlib
  - netCDF4
  - scikit-learn
  - seaborn
  - shapely
  - tqdm
  - xarray
  - xhistogram
  - pip
  - pip:
    - cmocean
    - pyxpcm
    - regionmask
    - hda
