name: bc-monitor
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy
  - cartopy
  - dask-ml<=2022.1.22
  - matplotlib
  - netCDF4
  - scikit-learn<1.1
  - seaborn
  - shapely
  - tqdm
  - xarray
  - xhistogram
  - pip
  - pip:
    - cmocean
    - git+https://github.com/obidam/pyxpcm.git@master
    - regionmask
    - hda
    - motuclient